-- ==============================================================================
-- ValueLens: Exploratory Data Analysis (EDA) Queries
-- Purpose: Initial business analysis and metric validation for the UK cohort.
-- Note: The `sales` table has already been cleaned and filtered to 'United Kingdom'.
-- ==============================================================================

-- 1. Total Revenue
-- Calculates the overall revenue generated by the cleaned cohort.
SELECT 
    ROUND(SUM(totalamount), 2) AS total_revenue
FROM sales;

-- 2. Number of Unique Customers
-- Counts the total number of distinct customers who made at least one purchase.
SELECT 
    COUNT(DISTINCT customerid) AS total_customers
FROM sales;

-- 3. Number of Transactions (Line Items)
-- Counts the total number of individual items purchased (row count).
SELECT 
    COUNT(*) AS total_transactions
FROM sales;

-- 4. Number of Unique Invoices
-- Counts the total number of distinct orders/invoices placed.
SELECT 
    COUNT(DISTINCT invoiceno) AS total_invoices
FROM sales;

-- 5. Average Order Value (AOV)
-- Calculates the average revenue per unique invoice.
SELECT 
    ROUND(SUM(totalamount) / COUNT(DISTINCT invoiceno), 2) AS average_order_value
FROM sales;

-- 6. Revenue by Country
-- Summarizes total revenue grouped by country (Expect only UK here).
SELECT 
    country,
    ROUND(SUM(totalamount), 2) AS total_revenue
FROM sales
GROUP BY country
ORDER BY total_revenue DESC;

-- 7. Customers by Country
-- Summarizes the unique customer count by country.
SELECT 
    country,
    COUNT(DISTINCT customerid) AS unique_customers
FROM sales
GROUP BY country
ORDER BY unique_customers DESC;

-- 8. Monthly Revenue
-- Analyzes seasonality and revenue trends over time by aggregating at the month level.
SELECT 
    STRFTIME('%Y-%m', invoicedate) AS invoice_month,
    ROUND(SUM(totalamount), 2) AS monthly_revenue
FROM sales
GROUP BY invoice_month
ORDER BY invoice_month ASC;

-- 9. Monthly Transaction Count
-- Analyzes transaction volume trends over time by month.
SELECT 
    STRFTIME('%Y-%m', invoicedate) AS invoice_month,
    COUNT(DISTINCT invoiceno) AS monthly_invoices,
    COUNT(*) AS monthly_line_items
FROM sales
GROUP BY invoice_month
ORDER BY invoice_month ASC;

-- 10. Top 20 Customers by Revenue
-- Identifies the highest-value customers based on lifetime revenue in the dataset.
SELECT 
    customerid,
    ROUND(SUM(totalamount), 2) AS total_revenue,
    COUNT(DISTINCT invoiceno) AS total_orders
FROM sales
GROUP BY customerid
ORDER BY total_revenue DESC
LIMIT 20;
